version: "2"
services:  
  db:
    image: geographica/postgis
    volumes:
      - pgdata:/data
      - ./maxmind:/maxmind
    ports: 
      - "5432:5432"
  geoip: 
    build: ./api
    ports: 
      - 3000:3000
    command: bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; npm run dev'
    depends_on:
      - db
    volumes:
      - ./api:/api
      - /api/src/node_modules
    environment:
      - PORT=3000 
volumes:
  pgdata: